Nm          Cleric~
WhoNm       Cle~
AtrPrm      4
Wpn         3700
Guild       3003
Sklladpt    95
Thac0       18
Thac47      9
Hpmin       7
Hpmax       10
Mana        1
Skll         42   1  70 'antimagic shell'
Skll          1   1  95 'armor'
Skll          5   1  95 'bless'
Skll          5   1  95 'blindness'
Skll         12   1  80 'call lightning'
Skll          9   1  95 'cause critical'
Skll          1   1  95 'cause light'
Skll          5   1  95 'cause serious'
Skll          2   1  95 'continual light'
Skll         13   1  95 'control weather'
Skll          8   1  95 'create buffet'
Skll          3   1  95 'create food'
Skll          2   1  95 'create water'
Skll          4   1  95 'cure blindness'
Skll          9   1  95 'cure critical'
Skll         13   1  95 'cure disease'
Skll          1   1  95 'cure light'
Skll          9   1  90 'cure poison'
Skll          5   1  95 'cure serious'
Skll         12   1  95 'curse'
Skll         20   1  95 'destroy cursed'
Skll          4   1  95 'detect evil'
Skll          4   1  95 'detect good'
Skll          7   1  95 'detect hidden'
Skll          5   1  95 'detect invis'
Skll          3   1  95 'detect magic'
Skll          5   1  95 'detect poison'
Skll         10   1  95 'dispel evil'
Skll         10   1  80 'dispel good'
Skll         31   1  95 'dispel magic'
Skll          7   1  95 'earthquake'
Skll         50   1  95 'ethereal funnel'
Skll         40   1  95 'exorcise'
Skll          2   1  95 'faerie fire'
Skll         14   1  95 'faerie fog'
Skll         13   1  95 'flamestrike'
Skll         35   2  95 'flaming shield'
Skll         12   1  95 'fly'
Skll         15   1  95 'harm'
Skll         14   1  95 'heal'
Skll         10   1  95 'identify'
Skll          9   1  80 'infravision'
Skll          5   1  95 'know alignment'
Skll         10   1  95 'locate object'
Skll         20   2  95 'mass heal'
Skll         17   1  95 'mass invis'
Skll         40   2  95 'mass vortex lift'
Skll         18   1  95 'mute'
Skll         35   2  95 'nexus'
Skll         17   1  95 'plague'
Skll          8   1  95 'poison'
Skll         30   2  95 'portal'
Skll          6   1  95 'protection evil'
Skll          6   1  80 'protection good'
Skll          3   1  95 'refresh'
Skll         12   1  95 'remove curse'
Skll         16   1  95 'remove silence'
Skll         13   1  95 'sanctuary'
Skll         35   2  95 'shock shield'
Skll          8   1  95 'summon'
Skll          1   1  95 'turn undead'
Skll         35   1  95 'wizard eye'
Skll          1   2  95 'bludgeons'
Skll         31   8  70 'brew'
Skll          1   1  99 'common'
Skll         25   8  50 'dodge'
Skll          1   1  99 'dwarven'
Skll          1   1  99 'elven'
Skll         37   5  95 'fast healing'
Skll          1   5  60 'flexible arms'
Skll          1   1  99 'gnomish'
Skll          1   1  99 'halfling'
Skll          1   1  99 'kobold'
Skll          1   6  50 'long blades'
Skll         37   5  95 'meditate'
Skll          5   1  95 'mount'
Skll          1   5  50 'pugilism'
Skll         33   2  20 'rescue'
Skll         32   5  60 'scribe'
Skll          5   3  95 'scrolls'
Skll         15   8  50 'second attack'
Skll         37   4  95 'shield block'
Skll          1   3  60 'short blades'
Skll          1   1  95 'stake'
Skll          7   3  95 'staves'
Ttle         0 Man~ Woman~
Ttle         1 Believer~ Believer~
Ttle         2 Attendant~ Attendant~
Ttle         3 Acolyte~ Acolyte~
Ttle         4 Novice~ Novice~
Ttle         5 Missionary~ Missionary~
Ttle         6 Adept~ Adept~
Ttle         7 Deacon~ Deaconess~
Ttle         8 Vicar~ Vicaress~
Ttle         9 Priest~ Priestess~
Ttle        10 Minister~ Lady Minister~
Ttle        11 Canon~ Canon~
Ttle        12 Levite~ Levitess~
Ttle        13 Curate~ Curess~
Ttle        14 Monk~ Nun~
Ttle        15 Healer~ Healess~
Ttle        16 Chaplain~ Chaplain~
Ttle        17 Expositor~ Expositress~
Ttle        18 Bishop~ Bishop~
Ttle        19 Arch Bishop~ Arch Lady of the Church~
Ttle        20 Patriarch~ Matriarch~
Ttle        21 Elder Patriarch~ Elder Matriarch~
Ttle        22 Grand Patriarch~ Grand Matriarch~
Ttle        23 Great Patriarch~ Great Matriarch~
Ttle        24 Demon Killer~ Demon Killer~
Ttle        25 Greater Demon Killer~ Greater Demon Killer~
Ttle        26 Cardinal of the Sea~ Cardinal of the Sea~
Ttle        27 Cardinal of the Earth~ Cardinal of the Earth~
Ttle        28 Cardinal of the Air~ Cardinal of the Air~
Ttle        29 Cardinal of the Ether~ Cardinal of the Ether~
Ttle        30 Cardinal of the Heavens~ Cardinal of the Heavens~
Ttle        31 High Priest of the Sea~ High Priestess of the Sea~
Ttle        32 High Priest of the Earth~ High Priestess of the Earth~
Ttle        33 High Priest of the Air~ High Priestess of the Air~
Ttle        34 High Priest of the Ether~ High Priestess of the Ether~
Ttle        35 High Priest of the Heavens~ High Priestess of the Heavens~
Ttle        36 Saviour of the Sea~ Saviour of the Sea~
Ttle        37 Saviour of the Earth~ Saviour of the Earth~
Ttle        38 Saviour of the Air~ Saviour of the Air~
Ttle        39 Saviour of the Ether~ Saviour of the Ether~
Ttle        40 Saviour of the Void~ Saviour of the Void~
Ttle        41 Supreme Cleric of Virtue~ Supreme Cleric of Virtue~
Ttle        42 Supreme Cleric of Humility~ Supreme Cleric of Humility~
Ttle        43 Supreme Cleric of Light~ Supreme Cleric of Light~
Ttle        44 Supreme Cleric of Power~ Supreme Cleric of Power~
Ttle        45 Avatar of an Immortal~ Avatar of an Immortal~
Ttle        46 Avatar of a Deity~ Avatar of a Deity~
Ttle        47 Avatar of a Supremity~ Avatar of a Supremity~
Ttle        48 Avatar of an Implementor~ Avatar of an Implementor~
Ttle        49 Master of all Divinity~ Mistress of all Divinity~
Ttle        50 Master of all Divinity~ Mistress of all Divinity~
Ttle        51 Master of all Divinity~ Mistress of all Divinity~
Ttle        52 Master of all Divinity~ Mistress of all Divinity~
Ttle        53 Master of all Divinity~ Mistress of all Divinity~
Ttle        54 Master of all Divinity~ Mistress of all Divinity~
Ttle        55 Master of all Divinity~ Mistress of all Divinity~
Ttle        56 Master of all Divinity~ Mistress of all Divinity~
Ttle        57 Master of all Divinity~ Mistress of all Divinity~
Ttle        58 Master of all Divinity~ Mistress of all Divinity~
Ttle        59 Master of all Divinity~ Mistress of all Divinity~
Ttle        60 Holy Hero~ Holy Heroine~
Ttle        61 Angel~ Angel~
Ttle        62 Deity~ Deity~
Ttle        63 Supreme Master~ Supreme Mistress~
Ttle        64 Implementor~ Implementress~
Pose         0 0 You feel very holy.~
Pose         0 1 $n looks very holy.~
Pose         1 0 You nonchalantly turn wine into water.~
Pose         1 1 $n nonchalantly turns wine into water.~
Pose         2 0 A halo appears over your head.~
Pose         2 1 A halo appears over $n's head.~
Pose         3 0 You recite words of wisdom.~
Pose         3 1 $n recites words of wisdom.~
Pose         4 0 Deep in prayer, you levitate.~
Pose         4 1 Deep in prayer, $n levitates.~
Pose         5 0 An angel consults you.~
Pose         5 1 An angel consults $n.~
Pose         6 0 Your body glows with an unearthly light.~
Pose         6 1 $n's body glows with an unearthly light.~
Pose         7 0 A spotlight hits you.~
Pose         7 1 A spotlight hits $n.~
Pose         8 0 Everyone levitates as you pray.~
Pose         8 1 You levitate as $n prays.~
Pose         9 0 A cool breeze refreshes you.~
Pose         9 1 A cool breeze refreshes $n.~
Pose        10 0 The sun pierces through the clouds to illuminate you.~
Pose        10 1 The sun pierces through the clouds to illuminate $n.~
Pose        11 0 The ocean parts before you.~
Pose        11 1 The ocean parts before $n.~
Pose        12 0 A thunder cloud kneels to you.~
Pose        12 1 A thunder cloud kneels to $n.~
Pose        13 0 The Burning Man speaks to you.~
Pose        13 1 The Burning Man speaks to $n.~
Pose        14 0 An eye in a pyramid winks at you.~
Pose        14 1 An eye in a pyramid winks at $n.~
Pose        15 0 Valentine Michael Smith offers you a glass of water.~
Pose        15 1 Valentine Michael Smith offers $n a glass of water.~
Pose        16 0 The great god Mota gives you a staff.~
Pose        16 1 The great god Mota gives $n a staff.~
End
