Nm          Mage~
WhoNm       Mag~
AtrPrm      3
Wpn         3701
Guild       3018
Sklladpt    95
Thac0       18
Thac47      6
Hpmin       6
Hpmax       8
Mana        1
Skll         20   1  95 'acid blast'
Skll         33   1  95 'acid breath'
Skll         17   1  95 'antimagic shell'
Skll         47   1  95 'aquiles power'
Skll          5   1  95 'armor'
Skll         30   1  95 'blazebane'
Skll         27   1  95 'blazeward'
Skll          8   1  95 'blindness'
Skll          5   1  95 'burning hands'
Skll         16   1  95 'chain lightning'
Skll         14   1  95 'charm person'
Skll          3   1  95 'chill touch'
Skll         11   1  95 'colour spray'
Skll         22   1  95 'cone of silence'
Skll          4   1  95 'continual light'
Skll         10   1  95 'control weather'
Skll         10   1  95 'create spring'
Skll         12   1  75 'curse'
Skll         20   1  95 'demon skin'
Skll          2   1  95 'detect invis'
Skll          2   1  95 'detect magic'
Skll         26   1  95 'dispel magic'
Skll         16   1  95 'dragon skin'
Skll          9   1  95 'dragon wit'
Skll         33   1  95 'eldritch sphere'
Skll         12   1  95 'enchant weapon'
Skll         13   1  95 'energy drain'
Skll         45   1  95 'ethereal funnel'
Skll          4   1  95 'faerie fire'
Skll         10   1  95 'faerie fog'
Skll         34   1  95 'fire breath'
Skll         15   1  95 'fireball'
Skll          7   1  95 'fly'
Skll         31   1  95 'frost breath'
Skll         35   1  95 'gas breath'
Skll          7   1  95 'giant strength'
Skll         10   1  95 'identify'
Skll          6   1  95 'infravision'
Skll         24   1  95 'inner warmth'
Skll          4   1  95 'invis'
Skll          8   1  95 'know alignment'
Skll          9   1  95 'lightning bolt'
Skll         32   1  95 'lightning breath'
Skll          6   1  95 'locate object'
Skll          1   1  95 'magic missile'
Skll         15   1  95 'mass invis'
Skll         25   1  95 'meteor swarm'
Skll         40   1  95 'nexus'
Skll         18   1  95 'pass door'
Skll         23   1  75 'plague'
Skll         35   1  95 'portal'
Skll         18   1  95 'razorbait'
Skll         11   1  80 'recharge item'
Skll          5   1  75 'refresh'
Skll         16   1  95 'remove alignment'
Skll         12   1  95 'sagacity'
Skll         13   1  95 'shield'
Skll          7   1  95 'shocking grasp'
Skll         14   1  95 'sleep'
Skll          9   1  95 'slink'
Skll         17   1  95 'stone skin'
Skll         23   1  95 'swordbait'
Skll          8   1  95 'teleport'
Skll          6   1  95 'trollish vigor'
Skll          1   1  95 'ventriloquate'
Skll         27   1  95 'vortex lift'
Skll          7   1  95 'weaken'
Skll         26   1  95 'winter mist'
Skll         35   1  95 'wizard eye'
Skll          1   5  50 'bludgeons'
Skll         27   1  95 'brew'
Skll          1   1  99 'common'
Skll         30   8  30 'dodge'
Skll          1   1  99 'dwarven'
Skll          1   1  99 'elven'
Skll         44  10  30 'enhanced damage'
Skll         37   8  70 'fast healing'
Skll          1   1  60 'flexible arms'
Skll          1   1  99 'gnomish'
Skll          1   1  99 'halfling'
Skll          1   1  99 'kobold'
Skll          1   6  50 'long blades'
Skll         20   5  95 'meditate'
Skll          7   1  95 'mount'
Skll         45   5  25 'peek'
Skll          1   8  50 'pugilism'
Skll         28   1 100 'scribe'
Skll          3   2  95 'scrolls'
Skll         10  10  45 'second attack'
Skll         37   6  70 'shield block'
Skll          1   2  95 'short blades'
Skll          1   1  85 'stake'
Skll          3   2  95 'staves'
Skll         15   1  95 'swim'
Skll          1   1  70 'talonous arms'
Skll         30   1  30 'third attack'
Skll          3   2  95 'wands'
Ttle         0 Man~ Woman~
Ttle         1 Apprentice of Magic~ Apprentice of Magic~
Ttle         2 Spell Student~ Spell Student~
Ttle         3 Scholar of Magic~ Scholar of Magic~
Ttle         4 Delver in Spells~ Delveress in Spells~
Ttle         5 Medium of Magic~ Medium of Magic~
Ttle         6 Scribe of Magic~ Scribess of Magic~
Ttle         7 Seer~ Seeress~
Ttle         8 Sage~ Sage~
Ttle         9 Illusionist~ Illusionist~
Ttle        10 Abjurer~ Abjuress~
Ttle        11 Invoker~ Invoker~
Ttle        12 Enchanter~ Enchantress~
Ttle        13 Conjurer~ Conjuress~
Ttle        14 Magician~ Witch~
Ttle        15 Creator~ Creator~
Ttle        16 Savant~ Savant~
Ttle        17 Magus~ Craftess~
Ttle        18 Wizard~ Wizard~
Ttle        19 Warlock~ War Witch~
Ttle        20 Sorcerer~ Sorceress~
Ttle        21 Elder Sorcerer~ Elder Sorceress~
Ttle        22 Grand Sorcerer~ Grand Sorceress~
Ttle        23 Great Sorcerer~ Great Sorceress~
Ttle        24 Golem Maker~ Golem Maker~
Ttle        25 Greater Golem Maker~ Greater Golem Maker~
Ttle        26 Maker of Stones~ Maker of Stones~
Ttle        27 Maker of Potions~ Maker of Potions~
Ttle        28 Maker of Scrolls~ Maker of Scrolls~
Ttle        29 Maker of Wands~ Maker of Wands~
Ttle        30 Maker of Staves~ Maker of Staves~
Ttle        31 Green Wizard~ Green Wizard~
Ttle        32 Brown Wizard~ Brown Wizard~
Ttle        33 Blue Wizard~ Blue Wizard~
Ttle        34 Red Wizard~ Red Wizard~
Ttle        35 Grey Wizard~ Grey Wizard~
Ttle        36 White Wizard~ White Wizard~
Ttle        37 Silver Wizard~ Silver Wizard~
Ttle        38 Gold Wizard~ Gold Wizard~
Ttle        39 Platinum Wizard~ Platinum Wizard~
Ttle        40 Diamond Wizard~ Diamond Wizard~
Ttle        41 Archmage of Rods~ Archmage of Rods~
Ttle        42 Archmage of Wands~ Archmage of Wands~
Ttle        43 Archmage of Staves~ Archmage of Staves~
Ttle        44 Archmage of Orbs~ Archmage of Orbs~
Ttle        45 Demon Summoner~ Demon Summoner~
Ttle        46 Greater Demon Summoner~ Greater Demon Summoner~
Ttle        47 Dragon Charmer~ Dragon Charmer~
Ttle        48 Greater Dragon Charmer~ Greater Dragon Charmer~
Ttle        49 Master of Demons~ Mistress of Demons~
Ttle        50 Master of Dragons~ Mistress of Dragons~
Ttle        51 Master of all Magic~ Mistress of all Magic~
Ttle        52 Master of all Magic~ Mistress of all Magic~
Ttle        53 Master of all Magic~ Mistress of all Magic~
Ttle        54 Master of all Magic~ Mistress of all Magic~
Ttle        55 Master of all Magic~ Mistress of all Magic~
Ttle        56 Master of all Magic~ Mistress of all Magic~
Ttle        57 Master of all Magic~ Mistress of all Magic~
Ttle        58 Master of all Magic~ Mistress of all Magic~
Ttle        59 Master of all Magic~ Mistress of all Magic~
Ttle        60 Mage Hero~ Mage Heroine~
Ttle        61 Angel of Magic~ Angel of Magic~
Ttle        62 Deity of Magic~ Deity of Magic~
Ttle        63 Supremity of Magic~ Supremity of Magic~
Ttle        64 Implementor~ Implementress~
Pose         0 0 You sizzle with energy.~
Pose         0 1 $n sizzles with energy.~
Pose         1 0 You turn into a butterfly, then return to your normal shape.~
Pose         1 1 $n turns into a butterfly, then returns to $s normal shape.~
Pose         2 0 Blue sparks fly from your fingers.~
Pose         2 1 Blue sparks fly from $n's fingers.~
Pose         3 0 Little red lights dance in your eyes.~
Pose         3 1 Little red lights dance in $n's eyes.~
Pose         4 0 A slimy green monster appears before you and bows.~
Pose         4 1 A slimy green monster appears before $n and bows.~
Pose         5 0 You turn everybody into a little pink elephant.~
Pose         5 1 You are turned into a little pink elephant by $n.~
Pose         6 0 A small ball of light dances on your fingertips.~
Pose         6 1 A small ball of light dances on $n's fingertips.~
Pose         7 0 Smoke and fumes leak from your nostrils.~
Pose         7 1 Smoke and fumes leak from $n's nostrils.~
Pose         8 0 The light flickers as you rap in magical languages.~
Pose         8 1 The light flickers as $n raps in magical languages.~
Pose         9 0 Your head disappears.~
Pose         9 1 $n's head disappears.~
Pose        10 0 A fire elemental singes your hair.~
Pose        10 1 A fire elemental singes $n's hair.~
Pose        11 0 The sky changes color to match your eyes.~
Pose        11 1 The sky changes color to match $n's eyes.~
Pose        12 0 The stones dance to your command.~
Pose        12 1 The stones dance to $n's command.~
Pose        13 0 The heavens and grass change colour as you smile.~
Pose        13 1 The heavens and grass change colour as $n smiles.~
Pose        14 0 Everyone's clothes are transparent, and you are laughing.~
Pose        14 1 Your clothes are transparent, and $n is laughing.~
Pose        15 0 A black hole swallows you.~
Pose        15 1 A black hole swallows $n.~
Pose        16 0 The world shimmers in time with your whistling.~
Pose        16 1 The world shimmers in time with $n's whistling.~
End
