Nm          Psionicist~
WhoNm       Psi~
AtrPrm      4
Wpn         3701
Guild       3151
Sklladpt    95
Thac0       18
Thac47      9
Hpmin       6
Hpmax       9
Mana        1
Skll         10   1  95 'adrenaline control'
Skll          6   1  95 'agitation'
Skll         17   1  95 'antimagic shell'
Skll         47   1  95 'aquiles power'
Skll         14   1  95 'aura sight'
Skll         21   1  95 'awe'
Skll          1   1  95 'ballistic attack'
Skll         18   1  95 'biofeedback'
Skll         11   1  95 'cell adjustment'
Skll         15   1  95 'combat mind'
Skll         28   1  95 'complete healing'
Skll          8   1  95 'control flames'
Skll          2   1  95 'create sound'
Skll         30   1  95 'death field'
Skll         20   1  95 'detonate'
Skll         27   1  95 'disintegrate'
Skll          9   1  95 'displacement'
Skll         16   1  95 'domination'
Skll          9   1  95 'dragon wit'
Skll         19   1  95 'ectoplasmic form'
Skll         13   1  95 'ego whip'
Skll         33   1  95 'eldritch sphere'
Skll         10   1  95 'energy containment'
Skll         14   1  95 'energy drain'
Skll         15   1  95 'enhance armor'
Skll          7   1  95 'enhanced strength'
Skll         45   1  95 'ethereal funnel'
Skll         11   1  95 'flesh armor'
Skll         13   1  95 'identify'
Skll         19   1  95 'inertial barrier'
Skll          5   1  95 'inflict pain'
Skll         12   1  95 'intellect fortress'
Skll         14   1  95 'invis'
Skll         10   1  95 'lend health'
Skll          3   1  95 'levitation'
Skll          6   1  95 'mental barrier'
Skll          2   1  95 'mind thrust'
Skll         45   1  95 'nexus'
Skll         40   1  95 'portal'
Skll          9   1  95 'project force'
Skll         17   1  95 'psionic blast'
Skll          8   1  95 'psychic crush'
Skll          4   1  95 'psychic drain'
Skll          5   1  95 'psychic healing'
Skll         18   1  95 'razorbait'
Skll         12   1  95 'sagacity'
Skll         11   1  95 'share strength'
Skll         12   1  95 'summon'
Skll         23   1  95 'swordbait'
Skll          7   1  95 'teleport'
Skll          1   1  95 'thought shield'
Skll         25   1  95 'ultrablast'
Skll         27   1  95 'vortex lift'
Skll         35   1  95 'wizard eye'
Skll          6   1  95 'chameleon power'
Skll          1   1  99 'common'
Skll         30   1  30 'dodge'
Skll          1   1  99 'dwarven'
Skll          1   1  99 'elven'
Skll         44   1  30 'enhanced damage'
Skll         37   1  70 'fast healing'
Skll          1   1  99 'gnomish'
Skll          1   1  99 'halfling'
Skll          3   1  95 'heighten senses'
Skll          1   1  99 'kobold'
Skll         20   1  95 'meditate'
Skll          7   1  95 'mount'
Skll          5   1  95 'scrolls'
Skll         10   1  45 'second attack'
Skll          2   1  95 'shadow form'
Skll         37   1  95 'shield block'
Skll          1   1  95 'stake'
Skll          9   1  95 'staves'
Skll         30   1  30 'third attack'
Ttle         0 Man~ Woman~
Ttle         1 Psychic~ Psychic~
Ttle         2 Medium~ Medium~
Ttle         3 Gypsy~ Gypsy~
Ttle         4 Meditator~ Meditator~
Ttle         5 Mind Prober~ Mind Prober~
Ttle         6 Soul Searcher~ Soul Searcher~
Ttle         7 Astral Voyager~ Astral Voyager~
Ttle         8 Seeker~ Seeker~
Ttle         9 Empath~ Empath~
Ttle        10 Mind Reader~ Mind Reader~
Ttle        11 Telepath~ Telepath~
Ttle        12 Mental Adept~ Mental Adept~
Ttle        13 Spoonbender~ Spoonbender~
Ttle        14 Perceptive~ Perceptive~
Ttle        15 Clever~ Clever~
Ttle        16 Wise~ Wise~
Ttle        17 Genius~ Genius~
Ttle        18 Oracle~ Oracle~
Ttle        19 Soothsayer~ Soothsayer~
Ttle        20 Truthteller~ Truthteller~
Ttle        21 Sage~ Sage~
Ttle        22 Master Psychic~ Mistress Psychic~
Ttle        23 Master Meditator~ Mistress Meditator~
Ttle        24 Master Empath~ Mistress Empath~
Ttle        25 Master Clairvoyant~ Mistress Clairvoyant~
Ttle        26 Master Mind Reader~ Mistress Mind Reader~
Ttle        27 Master Telepath~ Mistress Telepath~
Ttle        28 Master Spoonbender~ Mistress Spoonbender~
Ttle        29 Grand Master Psychic~ Grand Mistress Psychic~
Ttle        30 Grand Master Meditator~ Grand Mistress Meditator~
Ttle        31 Grand Master Empath~ Grand Mistress Empath~
Ttle        32 Grand Master Clairvoyant~ Grand Mistress Clairvoyant~
Ttle        33 Grand Master Mind Reader~ Grand Mistress Mind Reader~
Ttle        34 Grand Master Telepath~ Grand Mistress Telepath~
Ttle        35 Grand Master Spoonbender~ Grand Mistress Spoonbender~
Ttle        36 Supreme Psychic~ Supreme Psychic~
Ttle        37 Supreme Meditator~ Supreme Meditator~
Ttle        38 Supreme Empath~ Supreme Empath~
Ttle        39 Supreme Clairvoyant~ Supreme Clairvoyant~
Ttle        40 Supreme Mind Reader~ Supreme Mind Reader~
Ttle        41 Supreme Telepath~ Supreme Telepath~
Ttle        42 Supreme Spoonbender~ Supreme Spoonbender~
Ttle        43 Supreme Spoonbender~ Supreme Spoonbender~
Ttle        44 Supreme Spoonbender~ Supreme Spoonbender~
Ttle        45 Supreme Spoonbender~ Supreme Spoonbender~
Ttle        46 Supreme Spoonbender~ Supreme Spoonbender~
Ttle        47 Supreme Spoonbender~ Supreme Spoonbender~
Ttle        48 Supreme Spoonbender~ Supreme Spoonbender~
Ttle        49 Supreme Spoonbender~ Supreme Spoonbender~
Ttle        50 Supreme Spoonbender~ Supreme Spoonbender~
Ttle        51 Supreme Spoonbender~ Supreme Spoonbender~
Ttle        52 Supreme Spoonbender~ Supreme Spoonbender~
Ttle        53 Supreme Spoonbender~ Supreme Spoonbender~
Ttle        54 Supreme Spoonbender~ Supreme Spoonbender~
Ttle        55 Supreme Spoonbender~ Supreme Spoonbender~
Ttle        56 Supreme Spoonbender~ Supreme Spoonbender~
Ttle        57 Supreme Spoonbender~ Supreme Spoonbender~
Ttle        58 Supreme Spoonbender~ Supreme Spoonbender~
Ttle        59 Supreme Spoonbender~ Supreme Spoonbender~
Ttle        60 Psionicist Hero~ Psionicist Heroine~
Ttle        61 Psionicist Angel~ Psionicist Angel~
Ttle        62 Deity of Psionics~ Deity of Psionics~
Ttle        63 Supreme Psionicst~ Supreme Psionicist~
Ttle        64 Implementor~ Implementress~
Pose         0 0 Stop it with the Ouija board, will ya?~
Pose         0 1 Great, $n is playing with $s Ouija board again.~
Pose         1 0 You read everyone's mind....and shudder with disgust.~
Pose         1 1 $n reads your mind...eww, you pervert!~
Pose         2 0 You show everyone your awards for perfect school attendance~
Pose         2 1 You aren't impressed by $n's school attendance awards.  Geek.~
Pose         3 0 A will-o-the-wisp arrives with your slippers.~
Pose         3 1 A will-o-the-wisp arrives with $n's slippers.~
Pose         4 0 What's with the extra leg?~
Pose         4 1 Why did $n sprout an extra leg just now?~
Pose         5 0 The spoons flee as you begin to concentrate.~
Pose         5 1 The spoons flee as $n begins to concentrate.~
Pose         6 0 Stop wiggling your brain at people.~
Pose         6 1 Make $n stop wiggling $s brain at you!~
Pose         7 0 MENSA called...they want your opinion on something.~
Pose         7 1 MENSA just called $n for consultation.~
Pose         8 0 Chairs fly around the room at your slightest whim.~
Pose         8 1 Chairs fly around the room at $n's slightest whim.~
Pose         9 0 Oof...maybe you shouldn't summon any more hippopotamuses.~
Pose         9 1 Oof!  Guess $n won't be summoning any more hippos for a while.~
Pose        10 0 Oops...your hair is sizzling from thinking too hard.~
Pose        10 1 Oops...$n's hair is sizzling from thinking too hard.~
Pose        11 0 What?  You were too busy concentrating.~
Pose        11 1 What?  Oh, $n was lost in thought...again.~
Pose        12 0 Will you get down here before you get hurt?~
Pose        12 1 Quick, get a stick, $n is doing $s pinata impression again.~
Pose        13 0 Careful...don't want to disintegrate anyone!~
Pose        13 1 LOOK OUT!  $n is trying to disintegrate something!~
Pose        14 0 You run off at the mouth about 'mind over matter'.~
Pose        14 1 Yeah, yeah, mind over matter.  Shut up, $n.~
Pose        15 0 Thud.~
Pose        15 1 Thud.~
Pose        16 0 You charm the pants off everyone...and refuse to give them back.~
Pose        16 1 Your pants are charmed off by $n, and $e won't give them back.~
End
