Nm          Ranger~
WhoNm       Rng~
AtrPrm      1
Wpn         3702
Guild       3022
Sklladpt    5
Thac0       18
Thac47      6
Hpmin       11
Hpmax       15
Mana        1
Skll         20   1  85 'armor'
Skll         18   1  80 'bless'
Skll         40   1  65 'blindness'
Skll         37   1  85 'charm person'
Skll         35   1  90 'continual light'
Skll         32   1  90 'control weather'
Skll         36   1  85 'create food'
Skll         32   1  90 'create spring'
Skll          8   1  90 'create water'
Skll         18   1  90 'cure blindness'
Skll         36   1  85 'cure critical'
Skll         18   1  85 'cure light'
Skll         18   1  85 'cure poison'
Skll         48   1  80 'cure serious'
Skll         35   1  90 'detect evil'
Skll         43   1  90 'detect hidden'
Skll         25   1  85 'detect invis'
Skll         24   1  80 'detect magic'
Skll         18   1  90 'detect poison'
Skll         40   1  90 'dispel magic'
Skll         35   1  90 'faerie fire'
Skll         30   1  90 'giant strength'
Skll         24   1  75 'identify'
Skll         10   1  65 'infravision'
Skll         16   1  80 'invis'
Skll         49   1  90 'know alignment'
Skll         50   1  90 'locate object'
Skll         50   1  80 'pass door'
Skll         19   1  85 'poison'
Skll         21   1  60 'refresh'
Skll         29   1  90 'shield'
Skll         48   1  70 'sleep'
Skll         39   1  80 'stone skin'
Skll          1   1  80 'bludgeons'
Skll          1   1  99 'common'
Skll         24   1  90 'disarm'
Skll         24   1  85 'dodge'
Skll         10   1  90 'dual'
Skll          1   1  99 'dwarven'
Skll          1   1  99 'elven'
Skll         30   1  75 'enhanced damage'
Skll          1   1  40 'flexible arms'
Skll         40   1  70 'fourth attack'
Skll         16   1  90 'hide'
Skll          3   1  90 'kick'
Skll          1   1  85 'long blades'
Skll          2   1  90 'mount'
Skll         23   1  90 'parry'
Skll         35   1  60 'pick lock'
Skll          1   1  90 'pugilism'
Skll         42   1  60 'punch'
Skll         15   1  95 'rescue'
Skll         11   1  90 'scan'
Skll         23   1  90 'second attack'
Skll          1   1  40 'short blades'
Skll         16   1  90 'sneak'
Skll          1   1  95 'talonous arms'
Skll         30   1  90 'third attack'
Skll          6   1  90 'track'
Ttle         0 Man~ Woman~
Ttle         1 Runner~ Runner~
Ttle         2 Strider~ Strider~
Ttle         3 Scout~ Scout~
Ttle         4 Scout Master~ Scout Master~
Ttle         5 Courser~ Courser~
Ttle         6 Tracker~ Tracker~
Ttle         7 Guide~ Guidess~
Ttle         8 Pathfinder~ Pathfinder~
Ttle         9 Explorer~ Explorer~
Ttle        10 Hunter~ Huntess~
Ttle        11 Beastmaster~ Beastmistress~
Ttle        12 Falconer~ Falconess~
Ttle        13 Feralan~ Feralan~
Ttle        14 Guardian~ Guardian~
Ttle        15 Justifier~ Justifier~
Ttle        16 Stalker~ Stalker~
Ttle        17 Warden~ Warden~
Ttle        18 Herbalist~ Herbalist~
Ttle        19 Enviromentalist~ Enviromentalist~
Ttle        20 Journeyman~ Journeywoman~
Ttle        21 Traveller~ Traveller~
Ttle        22 Wanderer~ Wanderer~
Ttle        23 Ranger Squire~ Ranger Squiress~
Ttle        24 Ranger Knight~ Ranger Knight~
Ttle        25 Ranger Lord~ Ranger Lady~
Ttle        26 Goblin Slayer~ Goblin Slayer~
Ttle        27 Gnoll Slayer~ Gnoll Slayer~
Ttle        28 Ogre Slayer~ Ogre Slayer~
Ttle        29 Minotaur Slayer~ Minotaur Slayer~
Ttle        30 Giant Slayer~ Giant Slayer~
Ttle        31 Skylord~ Skylady~
Ttle        32 Waterlord~ Waterlady~
Ttle        33 Treelord~ Treelady~
Ttle        34 Friend of Dryads~ Friend of Dryads~
Ttle        35 Friend of Pixies~ Friend of Pixies~
Ttle        36 Friend of Elves~ Friend of Elves~
Ttle        37 Swamp Master~ Swamp Mistress~
Ttle        38 Desert Master~ Desert Mistress~
Ttle        39 Mountain Master~ Mountain Mistress~
Ttle        40 Forest Master~ Forest Mistress~
Ttle        41 Defender of Plants~ Defender of Plants~
Ttle        42 Defender of Animals~ Defender of Animals~
Ttle        43 Defender of the Earth~ Defender of the Earth~
Ttle        44 Defender of Nature~ Defender of Nature~
Ttle        45 Defender of the Realms~ Defender of the Realms~
Ttle        46 Lord of the Plants~ Lady of the Plants~
Ttle        47 Lord of the Animals~ Lady of the Animals~
Ttle        48 Lord of the Earth~ Lady of the Earth~
Ttle        49 Lord of Nature~ Lady of Nature~
Ttle        50 Lord of Nature~ Lady of Nature~
Ttle        51 Lord of Nature~ Lady of Nature~
Ttle        52 Lord of Nature~ Lady of Nature~
Ttle        53 Lord of Nature~ Lady of Nature~
Ttle        54 Lord of Nature~ Lady of Nature~
Ttle        55 Lord of Nature~ Lady of Nature~
Ttle        56 Lord of Nature~ Lady of Nature~
Ttle        57 Lord of Nature~ Lady of Nature~
Ttle        58 Lord of Nature~ Lady of Nature~
Ttle        59 Lord of Nature~ Lady of Nature~
Ttle        60 Ranger Hero~ Ranger Heroine~
Ttle        61 Angel of Nature~ Angel of Nature~
Ttle        62 Deity of Rangers~ Deity of Rangers~
Ttle        63 Supremity of Nature~ Supremity of Nature~
Ttle        64 Implementor~ Implementress~
Pose         0 0 ~
Pose         0 1 ~
Pose         1 0 ~
Pose         1 1 ~
Pose         2 0 ~
Pose         2 1 ~
Pose         3 0 ~
Pose         3 1 ~
Pose         4 0 ~
Pose         4 1 ~
Pose         5 0 ~
Pose         5 1 ~
Pose         6 0 ~
Pose         6 1 ~
Pose         7 0 ~
Pose         7 1 ~
Pose         8 0 ~
Pose         8 1 ~
Pose         9 0 ~
Pose         9 1 ~
Pose        10 0 ~
Pose        10 1 ~
Pose        11 0 ~
Pose        11 1 ~
Pose        12 0 ~
Pose        12 1 ~
Pose        13 0 ~
Pose        13 1 ~
Pose        14 0 ~
Pose        14 1 ~
Pose        15 0 ~
Pose        15 1 ~
Pose        16 0 ~
Pose        16 1 ~
End
