Nm          Thief~
WhoNm       Thi~
AtrPrm      2
Wpn         3701
Guild       3028
Sklladpt    85
Thac0       18
Thac47      3
Hpmin       8
Hpmax       13
Mana        0
Skll         19   1  70 'dragon wit'
Skll          1   5  95 'backstab'
Skll          1   1  70 'bludgeons'
Skll         18   1  95 'circle'
Skll          1   1  99 'common'
Skll         20   4  95 'dirt kicking'
Skll         10   6  90 'disarm'
Skll          1   1  95 'dodge'
Skll         40   1  85 'dual'
Skll          1   1  99 'dwarven'
Skll          1   1  99 'elven'
Skll         40   1  55 'enhanced damage'
Skll         27   1  95 'fast healing'
Skll          1   1  95 'flexible arms'
Skll         47   1  30 'fourth attack'
Skll          1   1  99 'gnomish'
Skll          1   1  99 'halfling'
Skll          1   1  85 'hide'
Skll          1   1  99 'kobold'
Skll          1   1  85 'long blades'
Skll          2   1  85 'mount'
Skll          1   1  95 'peek'
Skll          1   1  95 'pick lock'
Skll         13   1  85 'poison weapon'
Skll          1   1  90 'pugilism'
Skll         12   1  90 'scan'
Skll          7   1  95 'scrolls'
Skll         10   5  90 'second attack'
Skll         17   1  95 'shield block'
Skll          1   1  95 'short blades'
Skll          8   1  95 'snare'
Skll          1   1  95 'sneak'
Skll          1   1  95 'stake'
Skll         13   1  95 'staves'
Skll          1   1  95 'steal'
Ttle         0 Man~ Woman~
Ttle         1 Pilferer~ Pilferess~
Ttle         2 Footpad~ Footpad~
Ttle         3 Filcher~ Filcheress~
Ttle         4 Pick-Pocket~ Pick-Pocket~
Ttle         5 Sneak~ Sneak~
Ttle         6 Pincher~ Pincheress~
Ttle         7 Cut-Purse~ Cut-Purse~
Ttle         8 Snatcher~ Snatcheress~
Ttle         9 Sharper~ Sharpress~
Ttle        10 Rogue~ Rogue~
Ttle        11 Robber~ Robber~
Ttle        12 Magsman~ Magswoman~
Ttle        13 Highwayman~ Highwaywoman~
Ttle        14 Burglar~ Burglaress~
Ttle        15 Thief~ Thief~
Ttle        16 Knifer~ Knifer~
Ttle        17 Quick-Blade~ Quick-Blade~
Ttle        18 Killer~ Murderess~
Ttle        19 Brigand~ Brigand~
Ttle        20 Cut-Throat~ Cut-Throat~
Ttle        21 Spy~ Spy~
Ttle        22 Grand Spy~ Grand Spy~
Ttle        23 Master Spy~ Master Spy~
Ttle        24 Assassin~ Assassin~
Ttle        25 Greater Assassin~ Greater Assassin~
Ttle        26 Master of Vision~ Mistress of Vision~
Ttle        27 Master of Hearing~ Mistress of Hearing~
Ttle        28 Master of Smell~ Mistress of Smell~
Ttle        29 Master of Taste~ Mistress of Taste~
Ttle        30 Master of Touch~ Mistress of Touch~
Ttle        31 Master of Reality~ Mistress of Reality~
Ttle        32 Guildmaster of the Unseen~ Guildmistress of the Unseen~
Ttle        33 Guildmaster of Stealth~ Guildmistress of Stealth~
Ttle        34 Guildmaster of Assassination~ Guidlmistress of Assassination~
Ttle        35 High Guildmaster~ High Guildmistress~
Ttle        36 Brother of Patience~ Sister of Patience~
Ttle        37 Brother of the Dagger~ Sister of the Dagger~
Ttle        38 Brother of the Coin~ Sister of the Coin~
Ttle        39 Brother of the Shadows~ Sister of the Shadows~
Ttle        40 Brother of the Guild~ Sister of the Guild~
Ttle        41 Lord of the Wolf~ Lady of the Wolf~
Ttle        42 Lord of the Snake~ Lady of the Serpent~
Ttle        43 Lord of the Hawk~ Lady of the Hawk~
Ttle        44 Lord of the Panther~ Lady of the Panther~
Ttle        45 Crime Lord~ Crime Mistress~
Ttle        46 Infamous Crime Lord~ Infamous Crime Mistress~
Ttle        47 Greater Crime Lord~ Greater Crime Mistress~
Ttle        48 Master Crime Lord~ Master Crime Mistress~
Ttle        49 Godfather~ Godmother~
Ttle        50 Godfather~ Godmother~
Ttle        51 Godfather~ Godmother~
Ttle        52 Godfather~ Godmother~
Ttle        53 Godfather~ Godmother~
Ttle        54 Godfather~ Godmother~
Ttle        55 Godfather~ Godmother~
Ttle        56 Godfather~ Godmother~
Ttle        57 Godfather~ Godmother~
Ttle        58 Godfather~ Godmother~
Ttle        59 Godfather~ Godmother~
Ttle        60 Assassin Hero~ Assassin Heroine~
Ttle        61 Angel of Death~ Angel of Death~
Ttle        62 Deity of Assassins~ Deity of Assassins~
Ttle        63 Supreme Master~ Supreme Mistress~
Ttle        64 Implementor~ Implementress~
Pose         0 0 You perform a small card trick.~
Pose         0 1 $n performs a small card trick.~
Pose         1 0 You wiggle your ears alternately.~
Pose         1 1 $n wiggles $s ears alternately.~
Pose         2 0 You nimbly tie yourself into a knot.~
Pose         2 1 $n nimbly ties $mself into a knot.~
Pose         3 0 You juggle with daggers, apples, and eyeballs.~
Pose         3 1 $n juggles with daggers, apples, and eyeballs.~
Pose         4 0 You steal the underwear off every person in the room.~
Pose         4 1 Your underwear is gone!  $n stole it!~
Pose         5 0 The dice roll ... and you win again.~
Pose         5 1 The dice roll ... and $n wins again.~
Pose         6 0 You count the money in everyone's pockets.~
Pose         6 1 Check your money, $n is counting it.~
Pose         7 0 You balance a pocket knife on your tongue.~
Pose         7 1 $n balances a pocket knife on your tongue.~
Pose         8 0 You produce a coin from everyone's ear.~
Pose         8 1 $n produces a coin from your ear.~
Pose         9 0 You step behind your shadow.~
Pose         9 1 $n steps behind $s shadow.~
Pose        10 0 Your eyes dance with greed.~
Pose        10 1 $n's eyes dance with greed.~
Pose        11 0 You deftly steal everyone's weapon.~
Pose        11 1 $n deftly steals your weapon.~
Pose        12 0 The Grey Mouser buys you a beer.~
Pose        12 1 The Grey Mouser buys $n a beer.~
Pose        13 0 Everyone's pocket explodes with your fireworks.~
Pose        13 1 Your pocket explodes with $n's fireworks.~
Pose        14 0 Everyone discovers your dagger a centimeter from their eye.~
Pose        14 1 You discover $n's dagger a centimeter from your eye.~
Pose        15 0 Where did you go?~
Pose        15 1 Where did $n go?~
Pose        16 0 Click.~
Pose        16 1 Click.~
End
