Nm          Warrior~
WhoNm       War~
AtrPrm      1
Wpn         3702
Guild       3022
Sklladpt    85
Thac0       18
Thac47      0
Hpmin       11
Hpmax       15
Mana        0
Skll          8   1  85 'bash door'
Skll         12   1  95 'berserk'
Skll          1   1  95 'bludgeons'
Skll          1   1  99 'common'
Skll         25   1  95 'dirt kicking'
Skll         20   1  85 'disarm'
Skll         15   1  70 'dodge'
Skll         15   1  85 'dual'
Skll          1   1  99 'dwarven'
Skll          1   1  99 'elven'
Skll          1   1  95 'enhanced damage'
Skll         20   1  95 'fast healing'
Skll          1   1  40 'flexible arms'
Skll         20   1  90 'fourth attack'
Skll          1   1  99 'gnomish'
Skll          1   1  99 'halfling'
Skll          1   1  85 'kick'
Skll          1   1  99 'kobold'
Skll          1   1  95 'long blades'
Skll          3   1  85 'mount'
Skll          1   1  85 'parry'
Skll          1   1  95 'pugilism'
Skll          4   1  80 'rescue'
Skll         46   1  45 'scan'
Skll         10   1  95 'scrolls'
Skll          5   1  95 'second attack'
Skll          7   1  95 'shield block'
Skll          1   1  60 'short blades'
Skll          1   1  95 'stake'
Skll         20   1  95 'staves'
Ttle         0 Man~ Woman~
Ttle         1 Swordpupil~ Swordpupil~
Ttle         2 Recruit~ Recruit~
Ttle         3 Sentry~ Sentress~
Ttle         4 Fighter~ Fighter~
Ttle         5 Soldier~ Soldier~
Ttle         6 Warrior~ Warrior~
Ttle         7 Veteran~ Veteran~
Ttle         8 Swordsman~ Swordswoman~
Ttle         9 Fencer~ Fenceress~
Ttle        10 Combatant~ Combatess~
Ttle        11 Hero~ Heroine~
Ttle        12 Myrmidon~ Myrmidon~
Ttle        13 Swashbuckler~ Swashbuckleress~
Ttle        14 Mercenary~ Mercenaress~
Ttle        15 Swordmaster~ Swordmistress~
Ttle        16 Lieutenant~ Lieutenant~
Ttle        17 Champion~ Lady Champion~
Ttle        18 Dragoon~ Lady Dragoon~
Ttle        19 Cavalier~ Lady Cavalier~
Ttle        20 Knight~ Lady Knight~
Ttle        21 Grand Knight~ Grand Knight~
Ttle        22 Master Knight~ Master Knight~
Ttle        23 Paladin~ Paladin~
Ttle        24 Grand Paladin~ Grand Paladin~
Ttle        25 Demon Slayer~ Demon Slayer~
Ttle        26 Greater Demon Slayer~ Greater Demon Slayer~
Ttle        27 Dragon Slayer~ Dragon Slayer~
Ttle        28 Greater Dragon Slayer~ Greater Dragon Slayer~
Ttle        29 Underlord~ Underlord~
Ttle        30 Overlord~ Overlord~
Ttle        31 Master of the Sword~ Mistress of the Sword~
Ttle        32 Master of the Shield~ Mistress of the Shield~
Ttle        33 Master of the Cross~ Mistress of the Cross~
Ttle        34 Master of the Rings~ Mistress of the Rings~
Ttle        35 Master of the Battle~ Mistress of the Battle~
Ttle        36 Baron of Thunder~ Baroness of Thunder~
Ttle        37 Baron of Storms~ Baroness of Storms~
Ttle        38 Baron of Tornadoes~ Baroness of Tornadoes~
Ttle        39 Baron of Hurricanes~ Baroness of Hurricanes~
Ttle        40 Baron of Meteors~ Baroness of Meteors~
Ttle        41 Baron of the Eastern Plains~ Baroness of Meteors~
Ttle        42 Baron of the Western Mountains~ Baroness of Meteors~
Ttle        43 Baron of the Northern Reaches~ Baroness of Meteors~
Ttle        44 Baron of the Southern Seas~ Baroness of Meteors~
Ttle        45 Duke of Thunder~ Dutchess of Thunder~
Ttle        46 Duke of Storms~ Dutchess of Storms~
Ttle        47 Duke of Tornadoes~ Dutchess of Tornadoes~
Ttle        48 Duke of Hurricanes~ Dutchess of Hurricanes~
Ttle        49 Duke of Meteors~ Dutchess of Meteors~
Ttle        50 Knight of the Black Rose~ Dutchess of Meteors~
Ttle        51 Knight of the Red Rose~ Dutchess of Meteors~
Ttle        52 Knight of the White Rose~ Dutchess of Meteors~
Ttle        53 Knight of the Silver Moon~ Dutchess of Meteors~
Ttle        54 Knight of the Golden Sun~ Dutchess of Meteors~
Ttle        55 Squire of the Realm~ Dutchess of Meteors~
Ttle        56 Herald of the Realm~ Dutchess of Meteors~
Ttle        57 Knight of the Realm~ Dutchess of Meteors~
Ttle        58 Lord of the Realm~ Lady of the Realm~
Ttle        59 Highlord of the Realm~ Highlady of the Realm~
Ttle        60 Knight Hero~ Knight Heroine~
Ttle        61 Angel of War~ Angel of War~
Ttle        62 Deity of War~ Deity of War~
Ttle        63 Supreme Master of War~ Supreme Mistress of War~
Ttle        64 Implementor~ Implementress~
Pose         0 0 You show your bulging muscles.~
Pose         0 1 $n shows $s bulging muscles.~
Pose         1 0 You crack nuts between your fingers.~
Pose         1 1 $n cracks nuts between $s fingers.~
Pose         2 0 You grizzle your teeth and look mean.~
Pose         2 1 $n grizzles $s teeth and looks mean.~
Pose         3 0 You hit your head, and your eyes roll.~
Pose         3 1 $n hits $s head, and $s eyes roll.~
Pose         4 0 Crunch, crunch -- you munch a bottle.~
Pose         4 1 Crunch, crunch -- $n munches a bottle.~
Pose         5 0 ... 98, 99, 100 ... you do pushups.~
Pose         5 1 ... 98, 99, 100 ... $n does pushups.~
Pose         6 0 Arnold Schwarzenegger admires your physique.~
Pose         6 1 Arnold Schwarzenegger admires $n's physique.~
Pose         7 0 Watch your feet, you are juggling granite boulders.~
Pose         7 1 Watch your feet, $n is juggling granite boulders.~
Pose         8 0 Oomph!  You squeeze water out of a granite boulder.~
Pose         8 1 Oomph!  $n squeezes water out of a granite boulder.~
Pose         9 0 You pick your teeth with a spear.~
Pose         9 1 $n picks $s teeth with a spear.~
Pose        10 0 Everyone is swept off their foot by your hug.~
Pose        10 1 You are swept off your feet by $n's hug.~
Pose        11 0 Your karate chop splits a tree.~
Pose        11 1 $n's karate chop splits a tree.~
Pose        12 0 A strap of your armor breaks over your mighty thews.~
Pose        12 1 A strap of $n's armor breaks over $s mighty thews.~
Pose        13 0 A boulder cracks at your frown.~
Pose        13 1 A boulder cracks at $n's frown.~
Pose        14 0 Mercenaries arrive to do your bidding.~
Pose        14 1 Mercenaries arrive to do $n's bidding.~
Pose        15 0 Four matched Percherons bring in your chariot.~
Pose        15 1 Four matched Percherons bring in $n's chariot.~
Pose        16 0 Atlas asks you to relieve him.~
Pose        16 1 Atlas asks $n to relieve him.~
End
